CREATE TABLE `clock_revision_entries` (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'default',
  `surtitle` json DEFAULT NULL,
  `title` json NOT NULL,
  `subtitle` json DEFAULT NULL,
  `slug` json DEFAULT NULL,
  `description` json DEFAULT NULL,
  `content` json DEFAULT NULL,
  `blocks` json DEFAULT NULL,
  `sections` json DEFAULT NULL,
  `dates` json DEFAULT NULL,
  `attributes` json DEFAULT NULL,
  `properties` json DEFAULT NULL,
  `seo` json DEFAULT NULL,
  `playlist` json DEFAULT NULL,
  `duration` int unsigned NOT NULL DEFAULT '0',
  `order` int unsigned NOT NULL DEFAULT '0',
  `parent_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `media_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `site_id` bigint unsigned NOT NULL DEFAULT '1',
  `user_id` bigint unsigned NOT NULL DEFAULT '1',
  `legacy_id` int unsigned DEFAULT NULL,
  `legacy_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `legacy_data` json DEFAULT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `title_nl` varchar(191) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (json_unquote(json_extract(`title`,_utf8mb4'$.nl'))) STORED,
  `title_en` varchar(191) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (json_unquote(json_extract(`title`,_utf8mb4'$.en'))) STORED,
  `slug_nl` varchar(191) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (json_unquote(json_extract(`slug`,_utf8mb4'$.nl'))) STORED,
  `slug_en` varchar(191) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (json_unquote(json_extract(`slug`,_utf8mb4'$.en'))) STORED,
  `active_episode_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS ((case when ((`type` = _utf8mb4'episode') and (`deleted_at` is null)) then `id` else NULL end)) STORED,
  `active_broadcast_episode_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS ((case when ((`type` = _utf8mb4'broadcast') and (`deleted_at` is null)) then `parent_id` else NULL end)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `entries_active_episode_id_uq` (`active_episode_id`),
  UNIQUE KEY `entries_unique_broadcast_start_per_site` (`site_id`,((case when ((`type` = _utf8mb4'broadcast') and (`deleted_at` is null)) then cast(json_unquote(json_extract(`dates`,_utf8mb4'$.start')) as datetime) else NULL end))),
  KEY `entries_type_index` (`type`),
  KEY `entries_parent_id_index` (`parent_id`),
  KEY `entries_image_id_index` (`image_id`),
  KEY `entries_media_id_index` (`media_id`),
  KEY `entries_site_id_index` (`site_id`),
  KEY `entries_type_site_parent_idx` (`type`,`site_id`,`parent_id`),
  KEY `entries_type_parent_published_idx` (`type`,`parent_id`,`published_at`),
  KEY `entries_site_type_del_created_idx` (`site_id`,`type`,`deleted_at`,`created_at`),
  KEY `entries_site_type_parent_del_created_idx` (`site_id`,`type`,`parent_id`,`deleted_at`,`created_at`),
  KEY `entries_parent_type_deleted_id_idx` (`parent_id`,`type`,`deleted_at`,`id`),
  KEY `entries_type_deleted_id_idx` (`type`,`deleted_at`,`id`),
  KEY `entries_active_broadcast_episode_idx` (`active_broadcast_episode_id`),
  KEY `entries_dates_start_index` ((cast(json_unquote(json_extract(`dates`,_utf8mb4'$.start')) as datetime))),
  CONSTRAINT `entries_cr_active_broadcast_episode_fk` FOREIGN KEY (`active_broadcast_episode_id`) REFERENCES `clock_revision_entries` (`active_episode_id`),
  CONSTRAINT `entries_cr_chk_active_broadcast_has_parent` CHECK (((`type` <> _utf8mb4'broadcast') or (`deleted_at` is not null) or (`parent_id` is not null))),
  CONSTRAINT `entries_cr_chk_active_episode_has_parent` CHECK (((`type` <> _utf8mb4'episode') or (`deleted_at` is not null) or (`parent_id` is not null))),
  CONSTRAINT `entries_cr_chk_broadcast_start_datetime` CHECK (((`type` <> _utf8mb4'broadcast') or (`deleted_at` is not null) or ((json_unquote(json_extract(`dates`,_utf8mb4'$.start')) is not null) and (cast(json_unquote(json_extract(`dates`,_utf8mb4'$.start')) as datetime) is not null))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
